Tweakers/Tweakers/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Data;
using Oracle.ManagedDataAccess.Client;

namespace Tweakers.Models
{
    /// <summary>
    /// Model class for Product
    /// </summary>
    public class Product : DbContext
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string SKU { get; set; }
        public long EAN { get; set; }
        public double AverageReviewScore { get; set; }
        public double Price { get; set; }
        public ProductType ProductType { get; set; }
        public Category Category { get; set; }
        public List<ProductPicture> ProductPictures;
        public List<ProductSpecification> ProductSpecifications;
        public List<UserList> UserLists;
        public List<ProductReview> Reviews;
        public List<ShopPrice> ShopPrices;

        #region Constructors
        /// <summary>
        /// Constructor for getting a Product out of the database when the product doesn't have a ProductType
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        /// <param name="brand"></param>
        /// <param name="sku"></param>
        /// <param name="ean"></param>
        /// <param name="averageReviewScore"></param>
        /// <param name="price"></param>
        /// <param name="category"></param>
        /// <param name="productPictures"></param>
        /// <param name="productSpecifications"></param>
        /// <param name="userLists"></param>
        /// <param name="reviews"></param>
        /// <param name="shopPrices"></param>
        public Product(int id, string name, string brand, string sku, long ean, double averageReviewScore, double price, Category category,
            List<ProductPicture> productPictures, List<ProductSpecification> productSpecifications,
            List<UserList> userLists, List<ProductReview> reviews, List<ShopPrice> shopPrices)
        {
            ID = id;
            Name = name;
            Brand = brand;
            SKU = sku;
            EAN = ean;
            AverageReviewScore = averageReviewScore;
            Price = price;
            Category = category;
            ProductPictures = productPictures;
            ProductSpecifications = productSpecifications;
            UserLists = userLists;
            Reviews = reviews;
            ShopPrices = shopPrices;
        }

        /// <summary>
        /// Constructor for getting a Product out of the database
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        /// <param name="brand"></param>
        /// <param name="sku"></param>
        /// <param name="ean"></param>
        /// <param name="averageReviewScore"></param>
        /// <param name="price"></param>
        /// <param name="productType"></param>
        /// <param name="category"></param>
        /// <param name="productPictures"></param>
        /// <param name="productSpecifications"></param>
        /// <param name="userLists"></param>
        /// <param name="reviews"></param>
        /// <param name="shopPrices"></param>
        public Product(int id, string name, string brand, string sku, long ean, double averageReviewScore, double price, ProductType productType,
            Category category, List<ProductPicture> productPictures, List<ProductSpecification> productSpecifications,
            List<UserList> userLists, List<ProductReview> reviews, List<ShopPrice> shopPrices)
        {
            ID = id;
            Name = name;
            Brand = brand;
            SKU = sku;
            EAN = ean;
            AverageReviewScore = averageReviewScore;
            Price = price;
            Category = category;
            ProductType = productType;
            ProductPictures = productPictures;
            ProductSpecifications = productSpecifications;
            UserLists = userLists;
            Reviews = reviews;
            ShopPrices = shopPrices;
        }
        #endregion

        #region DatabaseMethods
        /// <summary>
        /// Databasemethod that gets all the Products that is in a certain Category.
        /// Puts all new Products in the directory and returns a list of Products.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public static List<Product> FindAllProductsInCategory(int id)
        {
            List<Product> products = new List<Product>();

            string query = "SELECT * " +
                           "FROM TBL_PRODUCT P " +
                           "INNER JOIN TBL_PRODUCT_CAT PC ON P.ID = PC.PRODUCT_ID " +
                           "INNER JOIN TBL_CATEGORY C ON PC.CATEGORY_ID = C.ID " +
                           "WHERE C.ID=:id";

            using (OracleConnection connection = CreateConnection())
            using (OracleCommand command = new OracleCommand(query, connection))
            {
                command.BindByName = true;
                command.Parameters.Add(new OracleParameter("id", id));

                using (OracleDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var dicId = GetProductIdFromDataRecord(reader);
                        if (!Dictionaries.Products.ContainsKey(dicId))
                        {
                            Dictionaries.Products.Add(dicId,
                                GetProductFromDataRecord(reader));
                        }
                        products.Add(Dictionaries.Products[dicId]);
                    }
                }
            }
            return products;
        }

        /// <summary>
        /// Databasemethod that gets all the Products that is in a certain UserList.
        /// Puts all new Products in the directory and returns a list of Products.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public static List<Product> FindAllProductsInUserList(int id)
        {
            List<Product> products = new List<Product>();

            string query = "SELECT * " +
                           "FROM TBL_PRODUCT P " +
                           "INNER JOIN TBL_PRODUCT_LIST PL ON P.ID = PL.PRODUCT_ID " +
                           "INNER JOIN TBL_LIST L ON L.ID = PL.LIST_ID " +
                           "WHERE L.ID=:id";

            using (OracleConnection connection = CreateConnection())
            using (OracleCommand command = new OracleCommand(query, connection))
            {
                command.BindByName = true;
                command.Parameters.Add(new OracleParameter("id", id));

                using (OracleDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        var dicId = GetProductIdFromDataRecord(reader);
                        if (!Dictionaries.Products.ContainsKey(dicId))
                        {
                            Dictionaries.Products.Add(dicId, GetProductFromDataRecord(reader));
                        }
                        products.Add(Dictionaries.Products[dicId]);
                    }
                }
            }
            return products;
        }

        /// <summary>
        /// Databasemethod that gets the average review score of a certain Product.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public static double GetProductAverageReviewScore(int id)
        {
            string query = "SELECT AVG(SCORE) " +
                           "FROM TBL_PRODUCT_REVIEW PR " +
                           "INNER JOIN TBL_REVIEW R ON PR.REVIEW_ID = R.ID " +
                           "INNER JOIN TBL_PRODUCT P ON R.PRODUCT_ID = P.ID " +
                           "WHERE P.ID=:id " +
                           "AND SCORE <= 5";

            using (OracleConnection connection = CreateConnection())
            using (OracleCommand command = new OracleCommand(query, connection))
            {
                command.BindByName = true;
                command.Parameters.Add(new OracleParameter("id", id));

                using (OracleDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        if (!reader.IsDBNull(0))
                        {
                            return reader.GetDouble(0);
                        }
                    }
                }
            }
            return 0.00;
        }

        /// <summary>
        /// Databasemethod that gets the lowest product price of a certain Product.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public static double GetProductPrice(int id)
        {
            string query = "SELECT MIN(PRICE) " +
                           "FROM TBL_SHOP_PRODUCT SP " +
                           "INNER JOIN TBL_PRODUCT P ON SP.PRODUCT_ID = P.ID " +
                           "WHERE P.ID=:id";

            using (OracleConnection connection = CreateConnection())
            using (OracleCommand command = new OracleCommand(query, connection))
            {
                command.BindByName = true;
                command.Parameters.Add(new OracleParameter("id", id));

                using (OracleDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        if (!reader.IsDBNull(0))
                        {
                            return reader.GetDouble(0);
                        }
                    }
                }
            }
            return 0.00;
        }

        /// <summary>
        /// Databasemethod that returns a Product instance from a database.
        /// </summary>

Tweakers/Tweakers/Models/ProductType.cs
using System;
using System.Collections.Generic;
using System.Data;
using Oracle.ManagedDataAccess.Client;

namespace Tweakers.Models
{
    /// <summary>
    /// Model class for ProductType
    /// </summary>
    public class ProductType : DbContext
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public List<Product> Products;

        #region Constructor
        /// <summary>
        /// Constructor for getting a ProductType out of the database
        /// </summary>
        /// <param name="id"></param>
        /// <param name="name"></param>
        public ProductType(int id, string name)
        {
            ID = id;
            Name = name;
        }
        #endregion

        #region DatabaseMethods
        /// <summary>
        /// Databasemethod for finding a ProductType by ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public static ProductType FindById(int id)
        {
            string query = "SELECT * " +
                           "FROM TBL_PRODUCTTYPE " +
                           "WHERE ID=:id";

            using (OracleConnection connection = CreateConnection())
            using (OracleCommand command = new OracleCommand(query, connection))
            {
                command.BindByName = true;
                command.Parameters.Add(new OracleParameter("id", id));

                using (OracleDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        if (!reader.IsDBNull(0))
                        {
                            return GetProductTypeFromDataRecord(reader);
                        }
                    }
                }
            }
            return null;
        }

        /// <summary>
        /// Databasemethod that returns a ProductType instance from the database
        /// </summary>
        /// <param name="record"></param>
        /// <returns></returns>
        private static ProductType GetProductTypeFromDataRecord(IDataRecord record)
        {
            return new ProductType(
                Convert.ToInt32(record["ID"]),
                Convert.ToString(record["NAME"]));
        }

        #endregion
    }
}

Tweakers/Tweakers/Controllers/ProductController.cs
using System.Web.Mvc;
using Tweakers.Models;

namespace Tweakers.Controllers
{
    /// <summary>
    /// Controller class for Product
    /// </summary>
    public class ProductController : Controller
    {
        /// <summary>
        /// This is the ActionResult of the ProductCat View.
        /// It automatically generates all the products within a category
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View(Models.Product.FindAllProductsInCategory(id))</returns>
        public ActionResult ProductCat(int id)
        {
            return View(Models.Product.FindAllProductsInCategory(id));
        }

        /// <summary>
        /// This is the ActionResult of the Product View.
        /// It only contain a return View statement which redirects to the ShopPricesProduct
        /// and pass along the right product from the Dictionary..
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View("ShopPricesProduct", Dictionaries.Products[id])</returns>
        public ActionResult Product(int id)
        {
            return View("ShopPricesProduct", Dictionaries.Products[id]);
        }
        
        /// <summary>
        /// This ActionResult returns the ShopPricesProduct View.
        /// There all the shop prices of a product will be generated and shown.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View(Dictionaries.Products[id])</returns>
        public ActionResult ShopPricesProduct(int id)
        {
            return View(Dictionaries.Products[id]);
        }

        /// <summary>
        /// This ActionResult returns the SpecsProduct View.
        /// There all the specifications of a product will be generated and shown.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View(Dictionaries.Products[id])</returns>
        public ActionResult SpecsProduct(int id)
        {
            return View(Dictionaries.Products[id]);
        }

        /// <summary>
        /// This ActionResult returns the ReviewsProduct View.
        /// There all the reviews of a product will be generated and shown.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View(Dictionaries.Products[id])</returns>
        public ActionResult ReviewsProduct(int id)
        {
            return View(Dictionaries.Products[id]);
        }
    }
}

Tweakers/Tweakers/Controllers/UserListController.cs
using System.Web.Mvc;

namespace Tweakers.Controllers
{
    /// <summary>
    /// Controller class for UserList
    /// </summary>
    public class UserListController : Controller
    {
        /// <summary>
        /// This is the ActionResult for the WishList View
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult WishList(int id)
        {
            return View();
        }

        /// <summary>
        /// This is the ActionResult for the Inventory View
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Inventory(int id)
        {
            return View();
        }
    }
}

Tweakers/Tweakers/Views/Product/ProductCat.cshtml
@model List<Tweakers.Models.Product>

@{
    ViewBag.Title = Model[0].Category.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <p>Product</p>
                </th>
                <th>
                    <p>Review Score</p>
                </th>
                <th>
                    <p>Prijs</p>
                </th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count != 0)
            {
                foreach (var p in Model)
                {
                    <tr>
                        <td>
                            <p>@Html.ActionLink(p.Name + " " + p.SKU, "Product", new { id = p.ID })</p>
                        </td>
                        <td>
                            <p>Score: @p.AverageReviewScore</p>
                        </td>
                        <td>
                            <p>Prijs: @p.Price</p>
                        </td>
                    </tr>
                }
            }
            else
            {
                <h3>Sorry, er zijn nog geen producten beschikbaar binnen deze categorie :(</h3>
            }
        </tbody>
    </table>
</div>

Tweakers/Tweakers/Views/Product/ReviewsProduct.cshtml
@using Tweakers.Models
@model Tweakers.Models.Product

@{
    Layout = "~/Views/Product/_ProductLayout.cshtml";
}

<div class="writeReview">
    @Html.ActionLink("Schrijf een review!", "WriteReview", "ProductReview", new {id = Model.ID}, null)
</div>

<div class="reviews">
    @if (Model.Reviews.Count != 0)
    {
        foreach (var r in Model.Reviews)
        {
            <div class="thisReview">
                <div class="author">
                    <p>@r.User.Name</p>
                    <p id="date">@r.Date.ToString("dd-MM-yyyy")</p>
                </div>
                <div class="review">
                    <p>@r.Explanation</p>
                    <div class="score">
                        <table>
                            <thead>
                                <tr>
                                    <td>
                                        <b>Eindoordeel</b>
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <p>@r.Score</p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div id="assets">
                        <div class="pros">
                            <table>
                                <thead>
                                    <tr>
                                        <td>
                                            <b>Pluspunten</b>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var a in r.Assets)
                                    {
                                        if (a.Type == AssetType.Positive)
                                        {
                                            <tr>
                                                <td>
                                                    <p>@a.Explanation</p>
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="cons">
                            <table>
                                <thead>
                                    <tr>
                                        <td>
                                            <b>Minpunten</b>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var a in r.Assets)
                                    {
                                        if (a.Type == AssetType.Negative)
                                        {
                                            <tr>
                                                <td>
                                                    <p>@a.Explanation</p>
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <h3>Er zijn helaas geen reviews van dit product beschikbaar :(</h3>
    }
</div>

Tweakers/Tweakers/Views/Product/ShopPricesProduct.cshtml
@model Tweakers.Models.Product

@{
    Layout = "~/Views/Product/_ProductLayout.cshtml";
    //TODO: If there is time, implement IComparable for sorting
    //Model.ShopPrices.Sort();
}

<div class="shopPrices">
    <table class="table">
        <thead>
            <td>
                <p >Winkel</p>
            </td>
            <td>
                <p >Prijs</p>
            </td>
            <td></td>
        </thead>
        <tbody>
        @if (Model.ShopPrices.Count != 0)
        {
            foreach (var sp in Model.ShopPrices)
            {
                <tr>
                    <td class="spShop">
                        <a href="@sp.ProductURL">@sp.Shop.Name</a>
                    </td>
                    <td class="shopPrice">
                        <a href="@sp.ProductURL">@sp.Price</a>
                    </td>
                    <td class="WatchThis">
                        <a href="@sp.ProductURL">Bekijk!</a>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
    @if (Model.ShopPrices.Count == 0)
    {
        <h3>Sorry, er zijn helaas nog geen prijzen beschikbaar van dit product :(</h3>
    }
</div>

Tweakers/Tweakers/Views/Product/SpecsProduct.cshtml
@model Tweakers.Models.Product

@{
    Layout = "~/Views/Product/_ProductLayout.cshtml";
}

<div class="specTable">
    <table class="table">
        <thead>
            <td>
                <b>Specificatie</b>
            </td>
            <td>
                <b>Waarde</b>
            </td>
        </thead>
        <tbody>
            @foreach (var s in Model.ProductSpecifications)
            {
                <tr>
                    <td>
                        <p>@s.Name</p>
                    </td>
                    <td>
                        <p>@s.Value</p>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="pictures">
    <table class="pictureTable">
        <tbody>
            @foreach (var p in Model.ProductPictures)
            {
                <tr>
                    <td>
                        <img src="@p.PictureURL"/>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Tweakers/Tweakers/Views/Product/_ProductLayout.cshtml
@model Tweakers.Models.Product

@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
    var topPicture = Model.ProductPictures.First();
}

<h2>@ViewBag.Title</h2>
<div class="top">
    <div class="productOverview">
        <img class="productPicture" src="@topPicture.PictureURL" />
        <div class="specs">
            <p id="price">Prijs: @Model.Price</p>
            <p>@Html.ActionLink("Willen", "WishList", "UserList", new { id = Model.ID }, null)</p>
            <p>@Html.ActionLink("Hebben", "Inventory", "UserList", new { id = Model.ID }, null)</p>
        </div>
    </div>
    <div class="nav-tabs">
        <ul>
            <li>@Html.ActionLink("Prijzen", "ShopPricesProduct", "Product", new { id = Model.ID }, null)</li>
            <li>@Html.ActionLink("Specificaties", "SpecsProduct", "Product", new { id = Model.ID }, null)</li>
            <li>@Html.ActionLink("Reviews", "ReviewsProduct", "Product", new { id = Model.ID }, null)</li>
        </ul>
    </div>
</div>
<div class="render_body_content">
    @RenderBody()
</div>